### ISSUE TITLE
Server side traceback: _PassTheBaton._object is None

### ISSUE THREAD

**Issue by olli-shamlin** [olli-shamlin/flosetta#25]
There are some usage patterns that currently result in a server side traceback related to the BATON.  Here is one:

`Traceback (most recent call last):
  File "/Users/david/Documents/pycharm-projects/flosetta/venv/lib/python3.10/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/david/Documents/pycharm-projects/flosetta/venv/lib/python3.10/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/david/Documents/pycharm-projects/flosetta/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/david/Documents/pycharm-projects/flosetta/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/david/Documents/pycharm-projects/flosetta/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/david/Documents/pycharm-projects/flosetta/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/david/Documents/pycharm-projects/flosetta/app/routes.py", line 48, in quiz_setup
    BATON.object = create_quiz(Parameters(**t))
  File "/Users/david/Documents/pycharm-projects/flosetta/app/utils.py", line 127, in object
    assert _PassTheBaton._object is None
AssertionError
`

To create the above assertion error:

1. Setup a quiz & start it
2. Click the cancel button beside the progress bar
3. Set up another quiz & start it

Here is another way to trigger this assertion error:

1. Setup a quiz & start it
2. Use the NavBar menu to go to he quiz setup page
3. Set up another quiz & start it

I want to try to address this my converting the routes currently using BATON to use sessions instead.  Here are a a couple of references to how to use sessions:

- [How to use Flask-Session in Python Flask ?](https://www.geeksforgeeks.org/how-to-use-flask-session-in-python-flask/) on geeksforgeeks.org
- [Session data in Python Flask](https://pythonbasics.org/flask-sessions/) on pythonbasics.org

**Comment by olli-shamlin** [comment]
To attempt to address this issue, I'm experimenting with Flask's session object. 

I am storing a `Quiz` instance in the `session` object in `routes.quiz_setup()`.  As soon as control is given to `execute_quiz()` in the same module, I can see that the value associated with the 'quiz' key in the `session` object has been change from a `Quiz` instance to the `Quiz` in it's transport form.  However, I haven't been able to determine when/how this happens.

I have tried setting `repr=False` on the declarations of both `Quiz` and `MultipleChoiceQuiz` (which I'm using to test with), but that didn't change the behavior.  I think next I will try adding `__repr__` methods to both `Quiz` and `MultipleChoiceQuiz` to see if either of those get called.

**Comment by olli-shamlin** [comment]
Defining `__repr__` methods on `Quiz` and `MutlipleChoiceQuiz` bears no fruit.  Neither of these methods gets called between the time I set a session slot and get from the slot.

**Comment by olli-shamlin** [comment]
I gave the `Flask-Session` package a try and had more success.  In addition to installing `Flask-Session`, I also had to install the `cachelib` package.

This is working.  After getting Flask-Session installed and configured to use disk for persistence (might not be the most efficient storage option), I get back the same `Quiz` instance I store in a session.  

I suspect that my initial pass (ie, without `Flask-Session`) converted the `Quiz` instance to a dict was due to the fact that the info I was storing in the session was getting transmitted to the client to be stored as a cookie.

I am not going to commit/push these changes just yet.  Will let them soak while I continue to work on the quiz refactor (issue #22).

Files changed
- app/__init__.py
- app/routes.py
